services:

  postgres:
    image: postgres:16
    container_name: restaurant-booking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: restaurant_booking
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - restaurant-network


  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: restaurant-booking-frontend
    restart: unless-stopped

    working_dir: /app

    ports:
      - "4200:4200"

    volumes:
      - ./frontend:/app
      - angular_node_modules:/app/node_modules

    networks:
      - restaurant-network

    stdin_open: true
    tty: true

    command: sh


volumes:
  postgres_data:
  angular_node_modules:


networks:
  restaurant-network:
    driver: bridge