spring.application.name=restaurantbooking
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_booking
spring.datasource.username=restaurant_user
spring.datasource.password=restaurant_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect